### ISSUE TITLE
[Feature] Unified listener to watchfaces apps for general tasks

### ISSUE THREAD

**Issue by hpsaturn** [lunokjod/watch#6]
## Summary

Understanding the current WatchFace2, that is the main watchface now, it has a lot of code that maybe could be arrive from OS. For instance the Weather processing and its variables could get it from callback of the system, for example from some interface override of ApplicationBase class (LunoIotApplication). In the same way, the services status (WiFi, BLE, Battery and also maybe the time variables). All here in order to have a better alternatives to new watchfaces developers.

**Comment by lunokjod** [comment]
Is planed to move this watchface network tasks to the system and emit an event can be converted in callback via KVO, current a global variable is set, and Isn't the correct way

**Comment by hpsaturn** [comment]
resolved with last PR #7 and the new isolated tasks from @lunokjod
